# -*- coding: utf-8 -*-
"""ranking_news

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12vM7utSGYtc1ARmpPEInklLcOtWFQRbr
"""

!pip install beautifulsoup4
!pip install requests

import requests
from bs4 import BeautifulSoup

url = "https://news.naver.com/main/ranking/popularDay.naver?date=202204"

headers = {"User-Agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36"}
response = requests.get(url, headers=headers)

soup = BeautifulSoup(response.text, "html.parser")

rankingnews_boxs = soup.select('#wrap > div.rankingnews._popularWelBase._persist > div.rankingnews_box_wrap._popularRanking > div > div')
ranking_news_titles = []

name_inp = input()

for rankingnews_box in rankingnews_boxs:
    rankingnews_lists = rankingnews_box.select('ul > li')
    rankingnews_name = rankingnews_box.select_one('a > strong').text
    if rankingnews_name == name_inp:
      print('rankingnews_name :', rankingnews_name)

      for rankingnews_list in rankingnews_lists:
          rank = rankingnews_list.select_one('em').text
          title = rankingnews_list.select_one('div > a').text
          print(rank, '위 : ', title)