# -*- coding: utf-8 -*-
"""9조-[학생1_202255164].ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VlT9J1z1GMZrVmazew1nIRhqucMQ-b5G
"""

!pip install beautifulsoup4
!pip install requests

import requests
from bs4 import BeautifulSoup

url = "https://news.naver.com/main/ranking/popularDay.naver"

headers = {"User-Agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36"}

response = requests.get(url, headers=headers)

soup = BeautifulSoup(response.text, "html.parser")

rankingnews_boxes = soup.select('#wrap > div.rankingnews._popularWelBase._persist > div.rankingnews_box_wrap._popularRanking > div > div')
ranking_news_titles = []

for rankingnews_box in rankingnews_boxes:
    rankingnews_lists = rankingnews_box.select('ul > li')
    rankingnews_name = rankingnews_box.select_one('a > strong').text
    print('rankingnews_name :', rankingnews_name)
    for rankingnews_list in rankingnews_lists:
        rank = rankingnews_list.select_one('em').text
        title = rankingnews_list.select_one('div > a').text
        print(rank, '위 : ', title)
